### ISSUE TITLE
Information - Project description

### ISSUE THREAD

**Issue by Tranberry** [jvidziunas/Eldritch2#1]
I like that you actually did wrote a **readme.md** but I would love if it contained information on what this project is - without the need to find out by searching (google) elsewhere. I'm trying to not be rude as English is not my native language.

Keep coding and have a nice time / Oskar TRBRY

**Comment by jvidziunas** [comment]
Hey there, welcome and good suggestion. Currently working on the early versions of a Vulkan renderer, but I've made some changes to the readme which I'll sneak into the next commit.

For reference, this is a hobby 3D game engine project. No relation to Lovecraft, etc., but you can think of the name as referring to my coding style, if you like!

**Comment by jvidziunas** [comment]
Readme commit is live.
